### ISSUE TITLE
A Few Questions

### ISSUE THREAD

**Issue by Asheq** [kristijanhusak/vim-dirvish-git#2]
I'm trying out this plugin and for the most part it works great!

I do, however, have some questions/issues:

1. If the deleted file is not listed in the Dirvish buffer, how can it even be marked? Am I missing something?
2. I'm not seeing the Ignored symbol for ignored files.
3. I'm not seeing the Renamed symbol for renamed files. They are marked as Untracked while unstaged and then simply not marked at all after being staged.

I'm using NVIM v0.3.1.

Thanks for your help!

**Comment by kristijanhusak** [comment]
1. Yeah i guess you are right. Part of code was ported from the nerdtree git plugin, and this is part of it. I have removed it.
2. Yeah it's not showing because the status is not returning it. I have added it, just add `let g:dirvish_git_show_ignored = 1` to your vimrc.
3. It was a bug, should be fixed now.

**Comment by Asheq** [comment]
It's working now, thanks!
